### ISSUE TITLE
Grub seems to ignore local diversions for /etc/default/grub.

### ISSUE THREAD

**Issue by ypid** [debops/ansible-grub#10]
I now updated the second time the same template VM and during update of the `grub-pc` package, `dpkg` asks me if I want to install the new configuration file `/etc/default/grub`. Shouldn’t the local diversion avoid such questions?

```Shell
dpkg-divert --list|grep grub
local diversion of /etc/default/grub to /etc/default/grub.dpkg-divert
```

**Comment by drybjed** [comment]
It should. Perhaps it's an issue with `grub-pc` package?

**Comment by ypid** [comment]
Maybe. Can you check on next update if you are able to reproduce this?

**Comment by drybjed** [comment]
Sure, I'll try it out on a spare VM when I get the chance.

**Comment by ypid** [comment]
After reworking `debops.preseed` once again, I justed remembered this issue again and it suddenly made sense :smile:. The reason for this problem is that the not diverted configuration is [changed by the postinstall](https://github.com/debops/ansible-preseed/blob/fc3f995bfa92bc0dc20693b41b9eadc115134dfc/templates/srv/www/preseed/configs/d-i/debian.sh.j2#L21-L23) script when a system is installed using the preseed option (which is true for this VM). What do you think would be the best solution? I would propose to not touch `/etc/default/grub` via preseed and leave this task to the now existing `debops.grub` role? Can I change it that way?

**Comment by drybjed** [comment]
I've added these options in the preseed so that when a VM or a hardware host is installed and restarted, it's already ready for things like LXC containers and better I/O with `noop` elevator. Doing this via the `debops.grub` role would require an additional reboot for the options to take effect. That's why I wanted `debops.grub` to get the existing options and merge them in the new templated configuration so that the preseeded configuration could be carried over.

I wonder if `dpkg-divert` is available during the installation, and if so, could we do the diversion before modifying the original file, and just generate a new `/etc/default/grub`... I suppose the way we get the current options could be incorporated in that process so that any configuration passed by the user to the installed could be carried over. That would preserve the original `/etc/default/grub` diverted and hopefully make `grub-pc` package cooperate. What do you think? Although since the installer can modify the configuration as well, I wonder if the modified hash used to check the integrity is stored somewhere.

**Comment by ypid** [comment]
Thanks for explaining.

> That would preserve the original `/etc/default/grub` diverted

I have not considered that. Sounds good. I will try that, thanks.
